name: jd_jdfactory

on:
  workflow_dispatch:
  schedule:
    - cron: '6 */1 * * *'
  watch:
    types: started
  repository_dispatch:
    types: jd_jdfactory

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: npm install
        run: |
          npm install
      - name: '运行 【东东工厂】'
        run: |
          node onlyOneExecute.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE || github.event.client_payload.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG || github.event.client_payload.JD_DEBUG }}
          JD_USER_AGENT: ${{ secrets.JD_USER_AGENT || github.event.client_payload.JD_USER_AGENT }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN || github.event.client_payload.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID || github.event.client_payload.TG_USER_ID }}
          DDFACTORY_SHARECODES: ${{ secrets.DDFACTORY_SHARECODES || github.event.client_payload.DDFACTORY_SHARECODES }}
          SYNCURL: https://github.com/lxk0301/jd_scripts/raw/master/jd_jdfactory.js
