name: jd_joy

on:
  workflow_dispatch:
  schedule:
    - cron: '15 */2 * * *'
  watch:
    types: started
  repository_dispatch:
    types: jd_joy

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: npm install
        run: |
          npm install
      - name: '运行 【宠汪汪】'
        run: |
          node onlyOneExecute.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE || github.event.client_payload.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG || github.event.client_payload.JD_DEBUG }}
          JD_USER_AGENT: ${{ secrets.JD_USER_AGENT || github.event.client_payload.JD_USER_AGENT }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN || github.event.client_payload.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID || github.event.client_payload.TG_USER_ID }}
          JOY_FEED_COUNT: ${{ secrets.JOY_FEED_COUNT || github.event.client_payload.JOY_FEED_COUNT }}
          JOY_RUN_FLAG: ${{ secrets.JOY_RUN_FLAG || github.event.client_payload.JOY_RUN_FLAG }}
          SYNCURL: https://github.com/wintjade/un_break/raw/master/src/jd_joy.js

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 1
